import {
  ADMINLIST,
  DASHBOARD,
  GSTDELIVERYSLIP,
  GSTEXPENSEENTRY,
  GSTEXPENSELIST,
  GSTSALESENTRY,
  GSTSALESLIST,
  LOCALENTRY,
  LOCALEXPENSEAPPROVE,
  LOCALEXPENSEENTRY,
  LOCALHUBLIST,
  LOCALLIST,
  LOCALPAIDLIST,
  LOCALPARTYLIST,
  LOCALPENDINGLIST,
  LOCALPRODUCTIONLIST,
  OUTSTANDINGACCOUNT,
  OUTSTANDINGCASH,
  OUTSTANDINGGPAY,
  PRICELIST,
  QUOTATIONENTRY,
  QUOTATIONLIST,
} from "../router/paths";

import {
  AccountIcon,
  AdminIcon,
  ApproveListIcon,
  CashIcon,
  DashboardIcon,
  DeliveryIcon,
  EntryIcon,
  GpayIcon,
  GstExpenseIcon,
  GstSalesIcon,
  ListIcon,
  LocalExpenseIcon,
  LocalSalesIcon,
  OutstandingIcon,
  PartyIcon,
  PendingIcon,
  PriceListIcon,
  QuotationIcon,
} from "../components/icons";

export const ROLES = {
  SuperAdmin: "superadmin",
  Authenticated: "authenticated",
};

export const appConfig = [
  {
    type: "link",
    label: "Dashboard",
    icon: DashboardIcon,
    path: DASHBOARD,
    elementKey: "Dashboard",
    roles: [ROLES.SuperAdmin],
  },

  {
    type: "submenu",
    key: "localSales",
    label: "Local Sales",
    icon: LocalSalesIcon,
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
    children: [
      {
        label: "Entry",
        icon: EntryIcon,
        path: LOCALENTRY,
        elementKey: "LocalEntry",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "List",
        icon: ListIcon,
        path: LOCALLIST,
        elementKey: "LocalList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "Approved List",
        icon: ApproveListIcon,
        path: LOCALPAIDLIST,
        elementKey: "LocalPaidList",
        roles: [ROLES.SuperAdmin],
      },
      {
        label: "Pending List",
        icon: PendingIcon,
        path: LOCALPENDINGLIST,
        elementKey: "LocalPendingList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "Party List",
        icon: PartyIcon,
        path: LOCALPARTYLIST,
        elementKey: "LocalPartyList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
    ],
  },
  {
    type: "submenu",
    key: "localExpense",
    label: "Local Expense",
    icon: LocalExpenseIcon,
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
    children: [
      {
        label: "Entry",
        icon: EntryIcon,
        path: LOCALEXPENSEENTRY,
        elementKey: "LocalExpenseEntry",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "Approved",
        icon: ApproveListIcon,
        path: LOCALEXPENSEAPPROVE,
        elementKey: "LocalExpenseApprove",
        roles: [ROLES.SuperAdmin],
      },
      {
        label: "Production",
        icon: ListIcon,
        path: LOCALPRODUCTIONLIST,
        elementKey: "LocalProductionList",
        roles: [ROLES.SuperAdmin],
      },
      {
        label: "Hub",
        icon: ListIcon,
        path: LOCALHUBLIST,
        elementKey: "LocalHubList",
        roles: [ROLES.SuperAdmin],
      },
    ],
  },

  {
    type: "submenu",
    key: "gstSales",
    label: "GST Sales",
    icon: GstSalesIcon,
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
    children: [
      {
        label: "Entry",
        icon: EntryIcon,
        path: GSTSALESENTRY,
        elementKey: "GstEntry",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "List",
        icon: ListIcon,
        path: GSTSALESLIST,
        elementKey: "GstSalesList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "Delivery Slip",
        icon: DeliveryIcon,
        path: GSTDELIVERYSLIP,
        elementKey: "GstDeliverySlip",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
    ],
  },

  {
    type: "submenu",
    key: "gstExpense",
    label: "GST Expense",
    icon: GstExpenseIcon,
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
    children: [
      {
        label: "Entry",
        icon: EntryIcon,
        path: GSTEXPENSEENTRY,
        elementKey: "GstExpenseEntry",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "List",
        icon: ListIcon,
        path: GSTEXPENSELIST,
        elementKey: "GstExpenseList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
    ],
  },

  {
    type: "link",
    label: "Admin",
    icon: AdminIcon,
    path: ADMINLIST,
    elementKey: "AdminList",
    roles: [ROLES.SuperAdmin],
  },

  {
    type: "submenu",
    key: "quotation",
    label: "Quotation",
    icon: QuotationIcon,
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
    children: [
      {
        label: "Entry",
        icon: EntryIcon,
        path: QUOTATIONENTRY,
        elementKey: "QuotationEntry",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
      {
        label: "List",
        icon: ListIcon,
        path: QUOTATIONLIST,
        elementKey: "QuotationList",
        roles: [ROLES.SuperAdmin, ROLES.Authenticated],
      },
    ],
  },

  {
    type: "submenu",
    key: "outstanding",
    label: "Outstanding",
    icon: OutstandingIcon,
    roles: [ROLES.SuperAdmin],
    children: [
      {
        label: "Account",
        icon: AccountIcon,
        path: OUTSTANDINGACCOUNT,
        elementKey: "OutstandingAccount",
        roles: [ROLES.SuperAdmin],
      },
      {
        label: "GPay",
        icon: GpayIcon,
        path: OUTSTANDINGGPAY,
        elementKey: "OutstandingGpay",
        roles: [ROLES.SuperAdmin],
      },
      {
        label: "Cash",
        icon: CashIcon,
        path: OUTSTANDINGCASH,
        elementKey: "OutstandingCash",
        roles: [ROLES.SuperAdmin],
      },
    ],
  },

  {
    type: "link",
    label: "Price List",
    icon: PriceListIcon,
    path: PRICELIST,
    elementKey: "PriceList",
    roles: [ROLES.SuperAdmin, ROLES.Authenticated],
  },
];
